language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g pnpm
install:
  - pnpm install 
script:
  - pnpm build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./.vitepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main