name: release

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.29.2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build

      - name: SFTP SSH Action
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.DOC_SSH_HOST }}
          port: ${{ secrets.DOC_SSH_PORT }}
          password: ''
          username: ${{ secrets.DOC_SSH_USERNAME }}
          localPath: './vitepress/dist'
          remotePath: '~/service/html'
          privateKey: ${{ secrets.DOC_SSH_KEY }}

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DOC_SSH_HOST }}
          username: ${{ secrets.DOC_SSH_USERNAME }}
          port: ${{ secrets.DOC_SSH_PORT }}
          script: ${{ secrets.DOC_SSH_SCRIPT }}
