name: release

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.29.2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.DOC_SSH_HOST }}
          port: ${{ secrets.DOC_SSH_PORT }}
          username: ${{ secrets.DOC_SSH_USERNAME }}
          key: ${{ secrets.DOC_SSH_KEY }}
          source: "./.vitepress/dist/"
          target: "./service/html"
          overwrite: true

      - name: SSH Remote Commands
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DOC_SSH_HOST }}
          port: ${{ secrets.DOC_SSH_PORT }}
          username: ${{ secrets.DOC_SSH_USERNAME }}
          privateKey: ${{ secrets.DOC_SSH_KEY }}
          command: ${{ secrets.DOC_SSH_SCRIPT }}
